<?php
/**
 * Chatbot Window Template
 * 
 * This file only contains the necessary container for the chatbot.
 * All HTML elements are dynamically generated by the JavaScript.
 */

// Prevent direct access
defined('ABSPATH') or die('Access denied');

// Injection point for the chatbot. JavaScript will add all elements dynamically.
?>
<!-- Bloobee SmartChat Container (Content will be added by JavaScript) -->
<div id="bloobee-chat-root"></div>

<script>
    // Set chat icon URL if not set by WordPress settings
    if (!bloobeeAjax.settings.chat_icon_url || bloobeeAjax.settings.chat_icon_url.indexOf('chat-icon.png') > -1) {
        bloobeeAjax.settings.chat_icon_url = '<?php echo esc_url(BLOOBEE_SMARTCHAT_URL . "bloobee.png"); ?>';
    }
    
    // Set notification sound URL if not set
    if (!bloobeeAjax.settings.sound_url) {
        bloobeeAjax.settings.sound_url = '<?php echo esc_url(BLOOBEE_SMARTCHAT_URL . "public/sounds/message.mp3"); ?>';
    }
</script>
